name: Run tests on pull requests

on:
  pull_request:
    branches: [main]

jobs:
  pr-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    name: Testing on Python ${{ matrix.python-version }}
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.7.1
      - name: Install dependencies
        run: poetry install
      - name: Run ruff linter/formatter
        uses: astral-sh/ruff-action@v3
      - name: Run mypy
        run: poetry run mypy .
      - name: Run unit tests
        run: poetry run pytest tests -vv
